AnalysisTool/ViewModels/HomeViewModel.cs
using AnalysisTool.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AnalysisTool.ViewModels
{
    public class HomeViewModel
    {
        public User User { get; set; }
    }
}

AnalysisTool/Controllers/AssessmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AnalysisTool.Models;
using AnalysisTool.Persistence;
using AnalysisTool.Services;
using AnalysisTool.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace AnalysisTool.Controllers
{
    public class AssessmentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private AssessmentViewModel _model;

        public AssessmentController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _model = new AssessmentViewModel();
        }

        // GET: /<controller>/
        public IActionResult Mood()
        {
            return View();
        }


        // GET
        public IActionResult Assessment()
        {
            _model.Assessment = _unitOfWork.Assessments.SingleOrDefault(x => x.Name == "Mock Stroop Test");
            
            return View(_model);
        }

        public PartialViewResult _Template(AssessmentViewModel assessment)
        {  //Gets the requested parameter and returns the view page

            return PartialView(assessment);
        }

        public IActionResult Completed()
        {
            bool moreAssessments = true;

            return View(moreAssessments);
        }
    }
}

AnalysisTool/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AnalysisTool.Models;
using AnalysisTool.ViewModels;
using AnalysisTool.Persistence;

namespace AnalysisTool.Controllers
{
    public class HomeController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        private HomeViewModel _model;

        public HomeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _model = new HomeViewModel();
        }

        public IActionResult Index()
        {
            _model.User = _unitOfWork.Users.GetAll().First();
            
            return View(_model);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AnalysisTool/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AnalysisTool.Persistence;
using AnalysisTool.ViewModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace AnalysisTool.Controllers
{
    public class ReportController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private ReportViewModel _model;

        public ReportController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _model = new ReportViewModel();
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

AnalysisTool/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Fish Dreams - About";
}

<div class="row">
    <div class="text-center">
        <a href="@Url.Action("Index", "Home")" aria-label="Home">
            <i class="fa fa-home fa-3x"></i>
        </a>
    </div>
</div>


<div class="row padding-top">
    <div class="text-center">
        Description
    </div>
</div>

AnalysisTool/Views/Home/Index.cshtml
@model HomeViewModel

@{
    ViewData["Title"] = "Fish Dreams";
}

<div class="body-start navbar navbar-fixed-top row">
    <!-- Settings/User -->
    <div class="row padding-top">
        <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
        <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5">
            <h4>@Html.ActionLink("Settings", "Index", "Settings")</h4>
        </div>
        <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5 text-right">
            <h4>Hello, @Model.User.UserName</h4>
        </div>
        <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>

    </div>

    <!-- Center Start -->
    <div class="row padding-top">
        <div class="vertical-center text-center">
            
            <div class="row padding-top hidden-md hidden-lg"></div>
            <a href="@Url.Action("Mood", "Assessment")"><img src="~/images/start.png" style="width: 50%;"/></a>
            
        </div>
    </div>

    <!-- Footer -->
    <div class="navbar navbar-fixed-bottom row padding-bottom">

        <!-- Reports/About -->
        <div class="row">
            <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>

            <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5">
                <h4>@Html.ActionLink("Reports", "Index", "Report")</h4>
            </div>
            <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5 text-right">
                <h4>@Html.ActionLink("About", "About")</h4>
            </div>
            <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>

        </div>



    </div>



</div>

AnalysisTool/Views/Home/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body class="body-start">
    

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()        
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>

</html>